sudo: false
dist: trusty

language: scala

jdk:
  - oraclejdk8

env:
  global:
    - JABBA_HOME=/home/travis/.jabba

env:
  matrix:
    - SBT_CMD=";doc;safeUnitTests"
    - SBT_CMD="otherUnitTests"
    - SBT_CMD="scripted actions/*"
    - SBT_CMD="scripted api/*"
    - SBT_CMD="scripted compiler-project/*"
    - SBT_CMD="scripted dependency-management/*1of2"
    - SBT_CMD="scripted dependency-management/*2of2"
    - SBT_CMD="scripted ivy-deps-management/*"
    - SBT_CMD="scripted java/*"
    - SBT_CMD="scripted package/*"
    - SBT_CMD="scripted project/*1of2"
    - SBT_CMD="scripted project/*2of2"
    - SBT_CMD="scripted reporter/*"
    - SBT_CMD="scripted run/*"
    - SBT_CMD="scripted source-dependencies/*1of3"
    - SBT_CMD="scripted source-dependencies/*2of3"
    - SBT_CMD="scripted source-dependencies/*3of3"
    - SBT_CMD="scripted tests/*"
    - SBT_CMD="scripted project-load/*"
    - SBT_CMD="repoOverrideTest:scripted dependency-management/*"
    - SBT_CMD="mavenResolverPluginTest:scripted dependency-management/*2of2"
    - SBT_CMD="mavenResolverPluginTest:scripted dependency-management/*1of2 project/transitive-plugins"

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m -Dsbt.repository.secure=false "$SBT_CMD"

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - curl -L --fail https://piccolo.link/sbt-0.13.17.tgz > sbt-0.13.17.tgz
  - tar zxf ./sbt-0.13.17.tgz -C $HOME/
  - export PATH="$HOME/sbt/bin:$PATH"
  - $JABBA_HOME/bin/jabba install "zulu@1.6.107"
  - export JAVA_HOME="$JABBA_HOME/jdk/zulu@1.6.107"
  - export PATH="$JAVA_HOME/bin:$PATH"
  - java -version

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
