# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

    # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
    # which fortunately corresponds to current scalaz settings.
    # The line below can be used to cache a given sbt version.
    # - $HOME/.sbt/launchers/0.13.x

    # The line below is used to cache the scala version used by the build
    # job, as these versions might be replaced after a Travis CI build
    # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala

# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - openjdk6
#  - oraclejdk7

env:
  global:
    - JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxPermSize=256m"
  matrix:
    - SCRIPTED_TEST="scripted actions/*"
    - SCRIPTED_TEST="scripted api/*"
    - SCRIPTED_TEST="scripted compiler-project/*""
    - SCRIPTED_TEST="scripted dependency-management/*1of2"
    - SCRIPTED_TEST="scripted dependency-management/*2of2"
    - SCRIPTED_TEST="mavenResolverPluginTest:scripted dependency-management/*1of2 project/transitive-plugins"
    - SCRIPTED_TEST="mavenResolverPluginTest:scripted dependency-management/*2of2"
    - SCRIPTED_TEST="scripted java/*"
    - SCRIPTED_TEST="scripted package/*"
    - SCRIPTED_TEST="scripted project/*1of2"
    - SCRIPTED_TEST="scripted project/*2of2"
    - SCRIPTED_TEST="scripted reporter/*"
    - SCRIPTED_TEST="scripted run/*"
    - SCRIPTED_TEST="scripted source-dependencies/*1of3"
    - SCRIPTED_TEST="scripted source-dependencies/*2of3"
    - SCRIPTED_TEST="scripted source-dependencies/*3of3"
    - SCRIPTED_TEST="scripted tests/*"
    - SCRIPTED_TEST="scripted project-load/*"
    - SCRIPTED_TEST="safeUnitTests"
    - SCRIPTED_TEST="checkBuildScala211"

notifications:
  email:
    - eugene.yokota@typesafe.com
    - joshua.suereth@typesafe.com

script:
  - sbt "$SCRIPTED_TEST"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
