language: scala
script:
  - sbt "$SCRIPTED_TEST"
env:
  - SCRIPTED_TEST="scripted actions/*"
  - SCRIPTED_TEST="scripted api/*"
  - SCRIPTED_TEST="scripted compiler-project/*""
  - SCRIPTED_TEST="scripted dependency-management/*1of2"
  - SCRIPTED_TEST="scripted dependency-management/*2of2"
  - SCRIPTED_TEST="scripted java/*"
  - SCRIPTED_TEST="scripted package/*"
  - SCRIPTED_TEST="scripted project/*"
  - SCRIPTED_TEST="scripted reporter/*"
  - SCRIPTED_TEST="scripted run/*"
  - SCRIPTED_TEST="scripted source-dependencies/*1of3"
  - SCRIPTED_TEST="scripted source-dependencies/*2of3"
  - SCRIPTED_TEST="scripted source-dependencies/*3of3"
  - SCRIPTED_TEST="scripted tests/*"
  - SCRIPTED_TEST="all launcher/test main-settings/test main/test ivy/test logic/test completion/test"
  - SCRIPTED_TEST="all actions/test classpath/test collections/test incremental-compiler/test logging/test run/test task-system/test"
# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - openjdk6
notifications:
  email:
    - qbranch@typesafe.com
